# Generated by Django 5.1.5 on 2025-02-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.FloatField(verbose_name='Horsepower')),
                ('wt', models.FloatField(verbose_name='Weight (1000 lbs)')),
                ('cyl', models.IntegerField(verbose_name='Number of Cylinders')),
                ('predicted_mpg', models.FloatField(blank=True, null=True, verbose_name='Predicted MPG')),
            ],
        ),
    ]
